name: "Podcast Generator for iTunes"
author: "Pavlo Tarasiuk"
description: "Generates a feed for podcast from YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The commite's email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The commite's name
    required: true
    default: ${{ github.actor }}
